//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityFramework.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Komentari
    {
        public int id { get; set; }
        public string Sadrzaj { get; set; }
        public Nullable<System.DateTime> DatumKreiranja { get; set; }
        public Nullable<int> Likes { get; set; }
        public Nullable<int> Unlikes { get; set; }
        public Nullable<int> PostID { get; set; }
        public Nullable<int> KorisnikID { get; set; }
        public Nullable<int> isRazgovor { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Post Post { get; set; }
    }
}
