//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityFramework.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Komentari = new HashSet<Komentari>();
            this.Posts_Tags = new HashSet<Posts_Tags>();
            this.User_Likes = new HashSet<User_Likes>();
        }
    
        public int id { get; set; }
        public string Naslov { get; set; }
        public string Sadrzaj { get; set; }
        public string Tagovi { get; set; }
        public Nullable<System.DateTime> DatumKreiranja { get; set; }
        public Nullable<System.DateTime> DatumZadnjeIzmjene { get; set; }
        public Nullable<System.DateTime> DatumZadnjeAktivnosti { get; set; }
        public Nullable<System.DateTime> DatumZatvaranjaPosta { get; set; }
        public Nullable<int> PrihvaceniOdgovori { get; set; }
        public Nullable<int> BrojOdgovora { get; set; }
        public Nullable<int> BrojKomentara { get; set; }
        public Nullable<int> BrojOmiljenih { get; set; }
        public Nullable<int> BrojPregleda { get; set; }
        public Nullable<int> BrojPoena { get; set; }
        public Nullable<int> VlasnikID { get; set; }
        public string VlasnikNadimak { get; set; }
        public Nullable<int> PromijenioID { get; set; }
        public Nullable<int> RoditeljskiPostID { get; set; }
        public Nullable<int> PodKategorija { get; set; }
        public Nullable<int> PostVrsta { get; set; }
        public string SlikaURL { get; set; }
        public string temp { get; set; }
        public Nullable<int> Likes { get; set; }
        public Nullable<int> Unlikes { get; set; }
        public string Sazetak { get; set; }
        public Nullable<int> BrojRangiranja { get; set; }
        public Nullable<int> PrihvacenaIzmjena { get; set; }
        public string Podnaslov { get; set; }
        public Nullable<int> Broj_Razgovora { get; set; }
    
        public virtual ICollection<Komentari> Komentari { get; set; }
        public virtual Korisnik Korisnik { get; set; }
        public virtual PodKategorija PodKategorija1 { get; set; }
        public virtual ICollection<Posts_Tags> Posts_Tags { get; set; }
        public virtual ICollection<User_Likes> User_Likes { get; set; }
    }
}
