//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityFramework.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posts_Tags
    {
        public int id { get; set; }
        public Nullable<int> PostID { get; set; }
        public Nullable<int> TagID { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
