//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityFramework.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TriglavEntities : DbContext
    {
        public TriglavEntities()
            : base("name=TriglavEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bedz> Bedz { get; set; }
        public DbSet<Kategorija> Kategorija { get; set; }
        public DbSet<Komentari> Komentari { get; set; }
        public DbSet<Korisnik> Korisnik { get; set; }
        public DbSet<PodKategorija> PodKategorija { get; set; }
        public DbSet<Post> Post { get; set; }
        public DbSet<Posts_Tags> Posts_Tags { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Tag> Tag { get; set; }
        public DbSet<User_Likes> User_Likes { get; set; }
    }
}
