//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityFramework.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Likes
    {
        public int id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> PostId { get; set; }
        public Nullable<System.DateTime> DatumLajkanja { get; set; }
        public Nullable<int> isLiked { get; set; }
        public Nullable<int> Rate { get; set; }
        public Nullable<System.DateTime> DaumRated { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Post Post { get; set; }
    }
}
